[build]
  publish = "public"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(self), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), xr-spatial-tracking=(self)"

[[headers]]
  for = "*.usdz"
    [headers.values]
    Content-Type = "model/vnd.usdz+zip"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.glb"
    [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"
